config/routes.rb
MyTown::Application.routes.draw do
  resources :attractions

  resources :towns

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base

	belongs_to :town
	
	scope :all, order('name')
	
	before_save :find_attraction_coordinates
	
	def create_map_link(zoom=13,width=800,height=800)
		markers = ""; i = 1
		self.attractions.all.each do |attr|
			markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{attr.lat},#{attr.lon}"
			i += 1
		end
		map = "http://maps.google.com/maps/api/staticmap?center=#{lat},#{lon}&zoom=#{zoom}&size=#{width}x#{height}&maptype=#{markers}&sensor=false"
	end
	
	private
  
    def find_attraction_coordinates
      str = self.street
      town = self.town.name
      st = self.town.state
      coord = Geokit::Geocoders::GoogleGeocoder.geocode "#{str}, #{town}, #{st}"
      if coord.success
  	    self.lat, self.lon = coord.ll.split(',')
  	  else 
  	    errors.add_to_base("Error with geocoding")
  	  end
    end
end

app/models/town.rb
class Town < ActiveRecord::Base

	has_many :attractions, :dependent => :destroy

	STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']]

	scope :all, order('name')
	
	accepts_nested_attributes_for :attractions, :reject_if => lambda { |attraction| attraction[:name].blank? }
	
	before_save :find_town_coordinates
	
	def create_map_link(zoom=12,width=800,height=800)
		markers = ""; i = 1
		self.attractions.all.each do |attr|
			markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{attr.lat},#{attr.lon}"
			i += 1
		end
		map = "http://maps.google.com/maps/api/staticmap?center=#{lat},#{lon}&zoom=#{zoom}&size=#{width}x#{height}&maptype=#{markers}&sensor=false"
	end
	
	private
	
	def find_town_coordinates
		coord = Geokit::Geocoders::GoogleGeocoder.geocode "#{name}, #{state}"
		if coord.success
			self.lat, self.lon = coord.ll.split(',')
		else
			errors.add_to_base("Error with geocoding")
		end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  # GET /attractions
  # GET /attractions.xml
  def index
    @attractions = Attraction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attractions }
    end
  end

  # GET /attractions/1
  # GET /attractions/1.xml
  def show
    @attraction = Attraction.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/new
  # GET /attractions/new.xml
  def new
    @attraction = Attraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/1/edit
  def edit
    @attraction = Attraction.find(params[:id])
  end

  # POST /attractions
  # POST /attractions.xml
  def create
    @attraction = Attraction.new(params[:attraction])

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully created.') }
        format.xml  { render :xml => @attraction, :status => :created, :location => @attraction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attractions/1
  # PUT /attractions/1.xml
  def update
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      if @attraction.update_attributes(params[:attraction])
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.xml
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy

    respond_to do |format|
      format.html { redirect_to(attractions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  # GET /towns
  # GET /towns.xml
  def index
    @towns = Town.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @towns }
    end
  end

  # GET /towns/1
  # GET /towns/1.xml
  def show
    @town = Town.find(params[:id])
	@attraction = @town.attractions.all
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/new
  # GET /towns/new.xml
  def new
    @town = Town.new

	3.times {@town.attractions.build}
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @town }
    end
  end

  # GET /towns/1/edit
  def edit
    @town = Town.find(params[:id])
  end

  # POST /towns
  # POST /towns.xml
  def create
    @town = Town.new(params[:town])

    respond_to do |format|
      if @town.save
        format.html { redirect_to(@town, :notice => 'Town was successfully created.') }
        format.xml  { render :xml => @town, :status => :created, :location => @town }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /towns/1
  # PUT /towns/1.xml
  def update
    @town = Town.find(params[:id])

    respond_to do |format|
      if @town.update_attributes(params[:town])
        format.html { redirect_to(@town, :notice => 'Town was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @town.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.xml
  def destroy
    @town = Town.find(params[:id])
    @town.destroy

    respond_to do |format|
      format.html { redirect_to(towns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :town_id %><br />
    <%= f.text_field :town_id %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>Town</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attractions.each do |attraction| %>
  <tr>
    <td><%= attraction.name %></td>
    <td><%= attraction.street %></td>
    <td><%= attraction.town_id %></td>
    <td><%= attraction.lat %></td>
    <td><%= attraction.lon %></td>
    <td><%= link_to 'Show', attraction %></td>
    <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
    <td><%= link_to 'Destroy', attraction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attraction.name %>
</p>

<p>
  <b>Street:</b>
  <%= @attraction.street %>
</p>

<p>
  <b>Town:</b>
  <%= @attraction.town_id %>
</p>

<p>
  <b>Lat:</b>
  <%= @attraction.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @attraction.lon %>
</p>


<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTown</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/towns/_attraction_fields.html.erb
<div class="attraction">
	<p>
		Attraction:<br /><%= f.text_field :name %>
	</p>
	<p>
		Street Address:<br /><%= f.text_field :street %>
	</p>
</div>

app/views/towns/_form.html.erb
<%= form_for(@town) do |f| %>
  <% if @town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% @town.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/_town_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@town.errors.count, "error") %> prohibited this town from being saved:</h2>

  <ul>
  <% @town.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/towns/_town_fields.html.erb
<div class="field">
  The name of your town:<br />
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :state %>:<br />
  <%= f.select(:state, Town::STATES_LIST, :prompt => "Select ...") %>
</div>

<div class="field">
	What's so great about your town:
  <%# town_form.label :description %><br />
  <%= f.text_area :description, :cols => 30, :rows => 7 %>
</div>

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render 'form' %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<h1>Listing towns</h1>

<table>
  <tr>
    <th>Name</th>
    <th>State</th>
    <th>Description</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @towns.each do |town| %>
  <tr>
    <td><%= town.name %></td>
    <td><%= town.state %></td>
    <td><%= town.description %></td>
    <td><%= town.lat %></td>
    <td><%= town.lon %></td>
    <td><%= link_to 'Show', town %></td>
    <td><%= link_to 'Edit', edit_town_path(town) %></td>
    <td><%= link_to 'Destroy', town, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>Add your town to our system...</h1>

<% form_for(@town) do |town_form| %>
  <% if @town.errors.any? %>
		<%= render :partial => "town_errors" %>
  <% end %>
<table>
	<tr>
		<td width="400" valign="top">
			<p class="supertiny">&nbsp;</p>
			<%= render :partial => 'town_fields', :locals => { :f=>town_form } %>
			
			
		</td>
		<td width="400" valign="top">
			<p>List up to three attractions in your town:</p>				
			<% town_form.fields_for :attractions do |attraction_form| %>
				<%= render :partial => 'attraction_fields', :locals => { :f=>attraction_form } %>
				
				
			<% end %> 
		</td>
	</tr>
	<tr><td colspan="2" align="center"><br><%= town_form.submit "Add My Town to this awesome system" %></td></tr>
</table>
<% end %>


<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @town.name %>
</p>

<p>
  <b>State:</b>
  <%= @town.state %>
</p>

<p>
  <b>Description:</b>
  <%= @town.description %>
</p>

<p>
  <b>Lat:</b>
  <%= @town.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @town.lon %>
</p>

<p>
<b>Attractions in <%= @town.name %>:</b>
	<ol>
		<% for attraction in @attraction %>
			<li><%= attraction.name %> - <%= attraction.street %></li>
		<% end %>
	</ol>
</p>

<p>
	<%= image_tag @town.create_map_link %>
</p>

<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>